#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Display some rice info

foreground="\e[0;39m"
brown="\e[1;33m"

hostname="$(hostname)"
#distro="$(crux)"
kernel="$(uname -r -s)"
uptime="$(uptime -p | cut -d " " -f 2-)"
#packages="$(pkginfo -i | wc -l)"

#if [[ -n "$DISPLAY" ]]; then
#	xdo resize -h 190 -w 502
#fi

# Echo rice
echo -e " "
echo -e " "
echo -e "                   $brown$USER$foreground@$brown$hostname$foreground"
echo -e '       /\'
echo -e '      /  \'"         ${brown}Distro:$foreground    Arch punpun"
echo -e '     /    \'"        ${brown}Kernel:$foreground    Linux-4.0.2-punpun"
echo -e '    /˚̆̈̉` ˚̆̈̉` \'"       ${brown}Uptime:$foreground    $uptime"
echo -e '   /   レ   \'"      ${brown}Packages:$foreground  1951"
echo -e '  /     つ   \'"     ${brown}WM:$foreground        Gnome Shell"
echo -e ' /____________\'"    ${brown}Font:$foreground      Liberation 12"
echo -e ' ‾‾‾‾‾‾‾‾‾‾‾‾‾‾'
echo -e " "
echo -e " "
